### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by igorangst** [kushview/libjuce#1]
When I tried to build libjuice, I encountered an error. I'm under Ubuntu Studio 14.04. I attached the output of `./waf configure build`.
[log.txt](https://github.com/kushview/libjuce/files/142368/log.txt)

**Comment by mfisher31** [comment]
@igorangst This looks like you didn't pull down the the JUCE submodule. Try doing

`git submodule update --init --recursive`

and try again.  If that doesn't work, then there's a problem somewhere finding and/or parsing the juce_module files.

**Comment by igorangst** [comment]
This fixes the build. Thanks :-)

I didn't see there were empty submodules. Maybe this should go into the README or the configure script.

**Comment by mfisher31** [comment]
yep, I agree.  A quick note in the readme is a good idea for newcomers
